### PR TITLE
update brew tap caskroom/cask to brew tap homebrew/cask

### PR DESCRIPTION
**Pull request by dongrerohan421**
part of issue #258

### CODE REVIEW

**Comment by JoshuaGross** [comment]
Thanks, this fixed installation for me as well.

**Comment by nahuakang** [comment]
Thanks @dongrerohan421.  This helped. Would love to see this merged into master.

**Comment by dongrerohan421** [comment]
> Thanks @dongrerohan421. This helped. Would love to see this merged into master.

Great. I am glad it helped. 👍

**Comment by mparker3** [comment]
+1 @nahuakang

**Pull request closed without merging**
