### PR TITLE
docs: update readme

### PR DESCRIPTION
**Pull request by usmanity**
- update urls from http to https
- add note about leader key

### CODE REVIEW

**Review by SalvatoreT — APPROVED** [review]
Looks good! Thank you.

**Review by SalvatoreT — CHANGES_REQUESTED** [review]
Can you squash the commits?

**Comment by usmanity** [comment]
@SalvatoreT squashed commits

**Review by SalvatoreT — APPROVED** [review]

**Comment by SalvatoreT** [comment]
Thank you! Feel free to merge (or let me know if you need me to do it).

**Pull request merged**
